# Generated by Django 4.0.6 on 2022-10-28 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_statment',
            name='inv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.invoice'),
        ),
        migrations.AlterField(
            model_name='cust_statment',
            name='pay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.payment'),
        ),
    ]
