# Generated by Django 4.0.6 on 2022-10-31 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_paymentitems_inv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentitems',
            name='inv',
        ),
    ]
