# Generated by Django 4.0.6 on 2022-10-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_customer_opening_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='opening_balance',
            field=models.FloatField(null=True),
        ),
    ]
