# Generated by Django 4.0.6 on 2022-10-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_customer_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='opening_balance_due',
            field=models.FloatField(null=True),
        ),
    ]
