# Generated by Django 4.0.6 on 2022-10-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_customer_opening_balance_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='opnbalance_status',
            field=models.CharField(default='Default', max_length=100),
        ),
    ]
