# Generated by Django 4.0.6 on 2022-11-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_customer_opnbalance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gsttype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
