# Generated by Django 4.0.6 on 2022-11-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_invoice_gsttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtable',
            name='tax_rate',
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='purchase_cost',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
