# Generated by Django 4.0.4 on 2022-11-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_vendor_statment_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_statment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
