# Generated by Django 4.0.4 on 2022-11-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_vendor_statment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_statment',
            name='balance',
        ),
    ]
