# Generated by Django 4.0.4 on 2022-11-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_vendor_statment_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasebill_item',
            old_name='bid',
            new_name='bitem',
        ),
    ]
