# Generated by Django 4.0.4 on 2022-11-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_rename_bid_purchasebill_item_bitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasebill_item',
            old_name='bitem',
            new_name='bill',
        ),
    ]
