# Generated by Django 4.0.4 on 2022-11-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_rename_bitem_purchasebill_item_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder_item',
            old_name='pid',
            new_name='porder',
        ),
    ]
