# Generated by Django 4.0.4 on 2022-11-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_rename_pid_purchaseorder_item_porder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill_item',
            name='hsn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder_item',
            name='hsn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill_item',
            name='items',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
