# Generated by Django 4.0.4 on 2022-11-07 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_purchasebill_item_hsn_purchaseorder_item_hsn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchasedebit1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, null=True)),
                ('hsn', models.CharField(max_length=100, null=True)),
                ('quantity', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('tax', models.CharField(max_length=100, null=True)),
                ('total', models.CharField(max_length=100, null=True)),
                ('pdebit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasedebit')),
            ],
        ),
    ]
