# Generated by Django 4.0.4 on 2022-11-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_purchasedebit1'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayment1',
            name='duedate',
            field=models.DateField(null=True),
        ),
    ]
