# Generated by Django 4.0.4 on 2022-11-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_purchasepayment1_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='amtrecvd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='balance_due',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
