# Generated by Django 4.0.4 on 2022-11-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_remove_purchasebill_amtrecvd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='amtrecvd',
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='amtrecvd',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
