# Generated by Django 4.0.4 on 2022-11-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_remove_purchaseorder_amtrecvd_purchasebill_amtrecvd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment1',
            name='duedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
