# Generated by Django 4.0.4 on 2022-11-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_purchasepayment1_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment1',
            name='duedate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
