# Generated by Django 4.0.4 on 2022-11-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_alter_purchasebill_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='file',
            field=models.FileField(default='default.png', upload_to='purchase/bill'),
        ),
    ]
