# Generated by Django 4.0.4 on 2022-11-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_alter_purchasebill_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_expense',
            name='file',
            field=models.FileField(default='default.png', upload_to='purchase/expense'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='file',
            field=models.FileField(default='default.png', upload_to='purchase/purchaseorder'),
        ),
    ]
