# Generated by Django 4.0.4 on 2022-12-02 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_vendor_status_alter_accounts1_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255, null=True)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase_expense',
            name='destinofsupply',
        ),
        migrations.RemoveField(
            model_name='purchase_expense',
            name='gsttype',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='status',
        ),
        migrations.AddField(
            model_name='itemtable',
            name='itmdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='purchasebill_item',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor_statment',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts1',
            name='acctype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accounts1',
            name='deftaxcode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accounts1',
            name='detype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accounts1',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='creditperiod',
            name='newperiod',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cust_statment',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cust_statment',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='CGST',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='IGST',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='SGST',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='TCS',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='billingaddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='customer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimatedate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimateno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimatetotal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='expirationdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='placeofsupply',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='subtotal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='etransporter',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AlterField(
            model_name='ewayinv',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='account_sal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='acount_pur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='hsn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='inter_st',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='intra_st',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='item_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='pur_desc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='sale_desc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='sales_cost',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='stock',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='tax_reference',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='unit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amtapply',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amtcredit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='depto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pmethod',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentitems',
            name='balamount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentitems',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.payment'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='newmethod',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_expense',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='grand_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill_item',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchasedebit1',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sales_item',
            name='hsn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_item',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_item',
            name='product',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sales_item',
            name='salesorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.salesorder'),
        ),
        migrations.AlterField(
            model_name='sales_item',
            name='tax',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='CGST',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='IGST',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='SGST',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='TCS',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='placeofsupply',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='saleaddress',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='saledate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='saleemail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='salename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='saleno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='salestotal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipmentdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='subtotal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockadjust',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AlterField(
            model_name='unittable',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AlterField(
            model_name='unittable',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unittable',
            name='unit_symbol',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_statment',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.CreateModel(
            name='vendor_payment',
            fields=[
                ('vendorpymid', models.AutoField(primary_key=True, serialize=False, verbose_name='CUSTPYMID')),
                ('vendor', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100, null=True)),
                ('amount_received', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('paid_through', models.CharField(max_length=100)),
                ('ref_no', models.CharField(max_length=100, null=True)),
                ('account', models.CharField(max_length=100, null=True)),
                ('des', models.CharField(max_length=100, null=True)),
                ('running_bal', models.CharField(max_length=100)),
                ('accounts1id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.accounts1')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='profit_loss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=255, null=True)),
                ('acctyp', models.CharField(max_length=255, null=True)),
                ('accname', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('details1', models.CharField(blank=True, max_length=255, null=True)),
                ('details2', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('payments', models.FloatField(blank=True, null=True)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('expnc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchase_expense')),
                ('pbill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasebill')),
            ],
        ),
        migrations.CreateModel(
            name='item_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='', max_length=255)),
                ('qtyin', models.IntegerField(blank=True, null=True)),
                ('qtyout', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('bitm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasebill')),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('ditm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasedebit1')),
                ('initm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.invoice_item')),
                ('itm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.itemtable')),
            ],
        ),
        migrations.CreateModel(
            name='expense_banking',
            fields=[
                ('expenseid', models.AutoField(primary_key=True, serialize=False, verbose_name='exid')),
                ('date', models.DateField(null=True)),
                ('expenseaccount', models.CharField(max_length=100, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('vendor', models.CharField(max_length=100, null=True)),
                ('customer', models.CharField(max_length=100, null=True)),
                ('reference', models.CharField(max_length=100, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(default='default.png', upload_to='purchase/expense')),
                ('running_bal', models.CharField(max_length=100)),
                ('accounts1id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.accounts1')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='customer_payment',
            fields=[
                ('customerpymid', models.AutoField(primary_key=True, serialize=False, verbose_name='CUSTPYMID')),
                ('customer', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100, null=True)),
                ('amount_received', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('received_through', models.CharField(max_length=100)),
                ('paym_ref_no', models.CharField(max_length=100)),
                ('bnk_ref_no', models.CharField(max_length=100)),
                ('file', models.FileField(default='default.jpg', upload_to='Customer')),
                ('des', models.CharField(max_length=100, null=True)),
                ('running_bal', models.CharField(max_length=100)),
                ('accounts1id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.accounts1')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
