# Generated by Django 4.0.4 on 2022-12-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_alter_profit_loss_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profit_loss',
            old_name='acctyp',
            new_name='details0',
        ),
        migrations.AddField(
            model_name='profit_loss',
            name='inv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.invoice'),
        ),
        migrations.AddField(
            model_name='profit_loss',
            name='transaction',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
