# Generated by Django 4.0.4 on 2022-12-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_rename_acctyp_profit_loss_details0_profit_loss_inv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profit_loss',
            old_name='transaction',
            new_name='transactions',
        ),
    ]
