# Generated by Django 4.0.4 on 2022-12-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_alter_profit_loss_details2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit_loss',
            name='details2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
