# Generated by Django 4.0.4 on 2022-12-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_balancesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='cgst',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='igst',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='sgst',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
