# Generated by Django 4.0.4 on 2022-12-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_balancesheet_cgst_balancesheet_igst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='tds',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
