# Generated by Django 4.0.4 on 2022-12-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_balancesheet_tds'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='balancesheet',
            new_name='balance_sheet',
        ),
    ]
