# Generated by Django 4.0.4 on 2022-12-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_remove_balance_sheet1_bls_balance_sheet1_details1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance_sheet',
            name='payments',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balance_sheet1',
            name='payments',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
