# Generated by Django 4.0.4 on 2022-12-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_alter_balance_sheet_payments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance_sheet',
            name='accname',
        ),
        migrations.RemoveField(
            model_name='balance_sheet',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='balance_sheet',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='balance_sheet',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='balance_sheet',
            name='sgst',
        ),
        migrations.RemoveField(
            model_name='balance_sheet',
            name='tds',
        ),
    ]
