# Generated by Django 4.0.4 on 2022-12-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_remove_balance_sheet_accname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance_sheet',
            name='details0',
        ),
        migrations.DeleteModel(
            name='balance_sheet1',
        ),
    ]
