# Generated by Django 4.0.4 on 2022-12-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_remove_balance_sheet_details0_delete_balance_sheet1'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedebit',
            name='cgst',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasedebit',
            name='igst',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasedebit',
            name='sgst',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
