# Generated by Django 4.0.4 on 2022-12-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0052_balance_sheet_acctype_profit_loss_acctype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='grand_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='tcs_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
