# Generated by Django 4.0.4 on 2022-12-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_alter_invoice_grandtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit_loss',
            name='payments',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
