# Generated by Django 4.0.4 on 2022-12-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0057_purchasedebit1_cid_purchaseorder_item_cid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profit_loss',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='profit_loss',
            name='balance',
        ),
    ]
