# Generated by Django 4.0.2 on 2022-12-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0059_remove_customer_opening_balance_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='opening_balance_due',
            field=models.FloatField(null=True),
        ),
    ]
