# Generated by Django 4.0.2 on 2022-12-17 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0060_customer_opening_balance_due'),
    ]

    operations = [
        migrations.CreateModel(
            name='banking_payment',
            fields=[
                ('bnkpymid', models.AutoField(primary_key=True, serialize=False, verbose_name='BNK_PYM_ID')),
                ('customer', models.CharField(max_length=100, null=True)),
                ('vendor', models.CharField(max_length=100, null=True)),
                ('amount_received', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('received_through', models.CharField(max_length=100)),
                ('paym_ref_no', models.CharField(max_length=100)),
                ('bnk_ref_no', models.CharField(max_length=100)),
                ('file', models.FileField(default='default.jpg', upload_to='Customer')),
                ('des', models.CharField(max_length=100, null=True)),
                ('running_bal', models.CharField(max_length=100)),
                ('paid_through', models.CharField(max_length=100)),
                ('ref_no', models.CharField(max_length=100, null=True)),
                ('account', models.CharField(max_length=100, null=True)),
                ('expenseaccount', models.CharField(max_length=100, null=True)),
                ('reference', models.CharField(max_length=100, null=True)),
                ('pym_type', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('accounts1id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.accounts1')),
            ],
        ),
        migrations.CreateModel(
            name='salescreditnote',
            fields=[
                ('screditid', models.AutoField(primary_key=True, serialize=False, verbose_name='pdid')),
                ('credit_no', models.IntegerField(default=1000)),
                ('customer', models.CharField(max_length=100, null=True)),
                ('address', models.TextField(null=True)),
                ('creditdate', models.DateField(null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('supply', models.CharField(max_length=150, null=True)),
                ('billno', models.CharField(max_length=100, null=True)),
                ('subtotal', models.CharField(max_length=100, null=True)),
                ('taxamount', models.CharField(max_length=100, null=True)),
                ('grandtotal', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='salescreditnote1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, null=True)),
                ('hsn', models.CharField(max_length=100, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('tax', models.CharField(max_length=100, null=True)),
                ('total', models.CharField(max_length=100, null=True)),
                ('scredit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.salescreditnote')),
            ],
        ),
        migrations.RemoveField(
            model_name='expense_banking',
            name='accounts1id',
        ),
        migrations.RemoveField(
            model_name='expense_banking',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='vendor_payment',
            name='accounts1id',
        ),
        migrations.RemoveField(
            model_name='vendor_payment',
            name='cid',
        ),
        migrations.AddField(
            model_name='company',
            name='gstno',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='customer_payment',
        ),
        migrations.DeleteModel(
            name='expense_banking',
        ),
        migrations.DeleteModel(
            name='vendor_payment',
        ),
        migrations.AddField(
            model_name='salescreditnote',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AddField(
            model_name='banking_payment',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
    ]
