# Generated by Django 4.0.2 on 2022-12-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0061_banking_payment_salescreditnote_salescreditnote1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='tax_rate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
