# Generated by Django 4.0.2 on 2022-12-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0062_itemtable_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtable',
            name='tax_rate',
        ),
    ]
