# Generated by Django 4.0.4 on 2022-12-23 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0063_remove_itemtable_tax_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('qty', models.IntegerField(null=True)),
                ('transactions', models.CharField(max_length=100, null=True)),
                ('details', models.CharField(max_length=100, null=True)),
                ('details1', models.CharField(blank=True, default='', max_length=100)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasebill')),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('debit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasedebit')),
                ('inv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='mjournal1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('desc', models.TextField(null=True)),
                ('contact', models.CharField(max_length=100, null=True)),
                ('debit', models.FloatField(blank=True, default='0.0', null=True)),
                ('credit', models.FloatField(blank=True, default='0.0', null=True)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.DeleteModel(
            name='expense2',
        ),
        migrations.RemoveField(
            model_name='mjournal',
            name='account1',
        ),
        migrations.RemoveField(
            model_name='mjournal',
            name='account2',
        ),
        migrations.RemoveField(
            model_name='mjournal',
            name='contact1',
        ),
        migrations.RemoveField(
            model_name='mjournal',
            name='contact2',
        ),
        migrations.RemoveField(
            model_name='mjournal',
            name='credit1',
        ),
        migrations.RemoveField(
            model_name='mjournal',
            name='credit2',
        ),
        migrations.RemoveField(
            model_name='mjournal',
            name='debit1',
        ),
        migrations.RemoveField(
            model_name='mjournal',
            name='debit2',
        ),
        migrations.RemoveField(
            model_name='mjournal',
            name='desc1',
        ),
        migrations.RemoveField(
            model_name='mjournal',
            name='desc2',
        ),
        migrations.AddField(
            model_name='itemtable',
            name='stockin',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='itemtable',
            name='stockout',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='opblnc_due',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mjournal1',
            name='mjrnl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.mjournal'),
        ),
    ]
