# Generated by Django 4.0.4 on 2022-12-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0064_item_mjournal1_delete_expense2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance_sheet',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
