# Generated by Django 4.0.2 on 2023-01-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0067_otp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance_sheet',
            name='payments1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profit_loss',
            name='payments1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='status',
            field=models.CharField(default='Draft', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='deliver_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='deliver_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='reference',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
